# The test waits for cross-document toolchange propagation, which is unsupported.
[exposedTo-defaults-cross-origin.https.html]
  expected: TIMEOUT
  [Parent tool with no exposedTo array is not visible to cross-origin iframe]
    expected: TIMEOUT
  [Parent tool with empty exposedTo array is not visible to cross-origin iframe]
    expected: NOTRUN
  [Cross-origin iframe tool with default exposure is not visible to parent]
    expected: NOTRUN
  [Cross-origin iframe tool with empty exposedTo array is not visible to parent]
    expected: NOTRUN
